# Generated by Django 4.2.1 on 2023-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='agreed_to_submit',
            field=models.BooleanField(default=True),
        ),
    ]
